name: Build

on: [pull_request, workflow_dispatch]

jobs:
  # Stupid block cus reusable actions env block isn't supported yet.
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace
          gradle-version: release-candidate